#!/usr/bin/env bash

# Check for number of arguments passed
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Get script arguments
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Disable strict host key checking (not recommended for production)
ssh -o StrictHostKeyChecking=no -i "$ssh_key" "$username@$server_ip" "mkdir -p ~/" 2>/dev/null

# Transfer the file using scp
scp -i "$ssh_key" "$file_path" "$username@$server_ip:~/"

# Display success message
echo "File transferred successfully\!"
