#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
fw allow 'Nginx HTTP'
sed -i 's/.*listen\(.*\)80;/    listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
service nginx restart
