#!/usr/bin/env bash
# Installs nginx server
sudo apt-get update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
sed -i 's/.*listen\(.*\)80;/    listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
service nginx start
