#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html

# Define the redirection rule as a sed command
redirection_rule="\
location /redirect_me {
    return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

# Use sed to insert the redirection rule after the default server_name line
sudo sed -i "/server_name _;/a $redirection_rule" /etc/nginx/sites-enabled/default

sudo service nginx restart
