#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello world!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _:\n\trewrite ^\/redirect_me https://github.com\/nanakzy permanent:"

sudo sed -i "s/server_name _:/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server; error_page 404 /404.html; location = /404.html { root /var/www/html; internal; }"

sudo sed -i "s#listen 80 default_server;#$string_for_replacement#" /etc/nginx/sites-enabled/default

sudo service nginx restart
