#!/usr/bin/env bash
# Configures an Nginx server to add a custom HTTP response header

# Update package repositories
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create index.html with a simple message
echo "Hello world!" | sudo tee /var/www/html/index.html

# Configure custom HTTP response header
add_header X-Served-By $hostname;

# Add custom header configuration to Nginx default site configuration
sudo sed -i "/listen 80 default_server;/a $custom_header_config" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
