#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello world!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _:\n\trewrite ^\/redirect_me https://github.com/nanakzy:"

custom_header_config="add_header X-Served-By \$hostname;"
sudo sed -i "s/server_name _:/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server:\n\terror_page 404 \/404.html:\n\tlocation = \/404.html {\n\troot \/var/www/html:\n\t\tinternal:\n\t}"

sudo sed -i "s/listen 80 default_server:/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
