#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx
sudo sed -i '/server_name _;/a \ \ \ \ add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
