#!/usr/bin/env bash

# Install and configure HAProxy load balancer to 2135-lb-01
# Sends traffic to web-01 and web-02

CONFIG="\\\nlisten appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 403433-web-01 34.224.83.4:80 check\n\tserver 403433-web-02 54.89.108.197:80 check\n"

# Update package repository
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy management via init script
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

# Append HAProxy configuration to haproxy.cfg
sudo sed -i "\$a $CONFIG" /etc/haproxy/haproxy.cfg

# Start HAProxy service
sudo service haproxy start
