#!/usr/bin/env bash
# Install haproxy
CONF="\

frontend node
	 bind *:80
 	 mode http
    	 default_backend servers
    
backend servers
	balance roundrobin
	server 949-web-01 35.196.230.188:80 check
	server 949-web-02 34.73.178.142:80 check
"
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
sudo echo "$CONF" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
