#!/usr/bin/env bash
# Debug and configure nginx server to listen on port 80
sudo apt-get update
sudo apt-get -y install nginx
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx start
