#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

pid_file="/var/run/myscript.pid"

function handle_sigterm {
    echo "I hate the kill command"
    cleanup_and_exit
}

function handle_sigint {
    echo "Y U no love me?!"
}

function handle_sigquit {
    echo "Y U no love me?!"
    cleanup_and_exit
}

function cleanup_and_exit {
    rm -f "$pid_file"
    exit 0
}

trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

echo "$$" > "$pid_file"

while true; do
    echo "To infinity and beyond"
    sleep 2
done
