#!/usr/bin/env bash
# manages manage_my_process

pid_file="/var/run/my_process.pid"

case "$1" in
    start)
        if [ -e "$pid_file" ]; then
            echo "manage_my_process is already running. PID: $(cat "$pid_file")"
        else
            ./manage_my_process &   # Assuming the manage_my_process script is in the same directory
            echo "$!" > "$pid_file"
            echo "manage_my_process started"
        fi
        ;;
    stop)
        if [ -e "$pid_file" ]; then
            pid=$(cat "$pid_file")
            kill "$pid"
            rm -f "$pid_file"
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    restart)
        if [ -e "$pid_file" ]; then
            pid=$(cat "$pid_file")
            kill "$pid"
            rm -f "$pid_file"
            echo "manage_my_process stopped"
        fi
        ./manage_my_process &
        echo "$!" > "$pid_file"
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
