#!/usr/bin/env bash
# SSH client configuration

Host your_server_alias_or_IP
    HostName 54.172.20.170
    ubuntu
    IdentityFile ~/.ssh/school
    PreferredAuthentications publickey
    PasswordAuthentication no
